config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :clothes, only: [:new, :create]
  resources :blankets, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

has_many :bookings
devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_num, :address])

    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number, :address, :first_name, :last_name])
  end
end

app/controllers/blankets_controller.rb
class BlanketsController < ApplicationController
  def new
    if user_signed_in?
      @booking = current_user.bookings.build
      render partial: 'blankets/booking_form'
    else
      if params[:booking].present?
        session[:booking_params] = booking_params
      end
      redirect_to new_user_session_path
    end
  end

  def create
    if user_signed_in?
      @booking = current_user.bookings.build(booking_params)
    else
      redirect_to new_user_session_path and return unless session[:booking].present?

      @user = User.new(user_params)
      if @user.save
        sign_in(@user)
        @booking = @user.bookings.build(session[:booking_params])
      else
        render 'new'
        return
      end
    end

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:item_type, :quantity, :date, :time)
  end

  def user_params
    params.require(:user).permit(:name, :address, :phone_number)
  end
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  def new
    if user_signed_in?
      @booking = current_user.bookings.build
      render partial: 'clothes/booking_form'
    else
      if params[:booking].present?
        session[:booking_params] = booking_params
      end
      redirect_to new_user_session_path
    end
  end

  def create
    if user_signed_in?
      @booking = current_user.bookings.build(booking_params)
    else
      redirect_to new_user_session_path and return unless session[:booking_params].present?

      @user = User.new(user_params)
      if @user.save
        sign_in(@user)
        @booking = @user.bookings.build(session[:booking_params])
      else
        render 'new'
        return
      end
    end

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:item_type, :quantity, :date, :time)
  end

  def user_params
    params.require(:user).permit(:name, :address, :phone_number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blankets/_booking_form.html.erb
<%= simple_form_for @booking, url: blankets_path do |f| %>
  <h2>Select Service</h2>
  <!-- Form fields for service selection -->
  <%= f.input :item_type, collection: ["Cotton Blanket", "Wool Blanket", "Fleece Blanket"], include_blank: true, label: "Item Type" %>

  <%= f.input :quantity %>

  <%= f.button :submit, "Continue" %>
<% end %>

app/views/clothes/_booking_form.html.erb
<%= simple_form_for @booking, url: clothes_path do |f| %>
  <h2 class="yoyo">Select Service</h2>
  <div class="services-grid">
    <%= render partial: 'service_card', locals: { icon: 'fas fa-tshirt', label: 'T-Shirts', field_name: :tshirt_quantity, f: f } %>
    <%= render partial: 'service_card', locals: { icon: 'fas fa-tshirt', label: 'Shirts', field_name: :shirt_quantity, f: f } %>
    <%= render partial: 'service_card', locals: { icon: 'fas fa-vest', label: 'Vests', field_name: :vest_quantity, f: f } %>
    <%= render partial: 'service_card', locals: { icon: 'fas fa-pants', label: 'Pants', field_name: :pants_quantity, f: f } %>
  </div>
  <%= f.button :submit, "Continue", class: 'service-card-submit' %>
<% end %>

app/views/clothes/_service_card.html.erb
<div class="service-card">
  <div class="service-icon">
    <i class="<%= icon %>"></i>
  </div>
  <div class="service-info">
    <%= f.label field_name, label %>
    <%= f.number_field field_name, min: 0, value: 0, class: 'item-quantity' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDryCleaning</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

      <!-- FontAwesome CDN Link -->
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css', integrity: 'sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==', crossorigin: 'anonymous', referrerpolicy: 'no-referrer' %>

    <!-- AOS CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Stencil+Text&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">


    <!-- Scrollbar Settings -->
    <style>
      html::-webkit-scrollbar{
        width: 0.70vw;
      }

      html::-webkit-scrollbar-thumb{
        background: rgb(37, 37, 37);
        border-radius: 4px;
      }
    </style>
  </head>

  <body>
    <%= yield %>
      <p class="notice" style="display:none"><%= notice %></p>
      <p class="alert" style="display:none"><%= alert %></p>
    <!-- AOS JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script>
      AOS.init({
        duration: 600,
      });
    </script>

    <script>
      // ========== Navbar Function
      window.addEventListener("scroll", function(){
        const header = document.querySelector('header');
        header.classList.toggle("sticky", window.scrollY > 0);
      })
      // ========== Toggle Menu
      function toggleMenu(){
        const menuBar = document.querySelector(".menuToggle-rails");
        const nav = document.querySelector(".nav-rails");
        menuBar.classList.toggle('active');
        nav.classList.toggle('active');
      }
    </script>
  </body>
</html>